name: Auto Notif OneSignal

# Script ini HANYA jalan kalau ada file berakhiran .xml atau .zip yang di-upload
on:
  push:
    paths:
      - '**.xml'
      - '**.zip'

jobs:
  blast_notif:
    runs-on: ubuntu-latest
    steps:
      - name: Kirim Sinyal ke OneSignal
        run: |
          curl --request POST \
               --url https://onesignal.com/api/v1/notifications \
               --header 'Authorization: Basic ${{ secrets.ONESIGNAL_REST_API_KEY }}' \
               --header 'accept: application/json' \
               --header 'content-type: application/json' \
               --data '{
                 "app_id": "${{ secrets.ONESIGNAL_APP_ID }}",
                 "included_segments": ["Subscribed Users"],
                 "headings": {"en": "🔥 Update Keybox Baru!"},
                 "contents": {"en": "Siroha baru saja mengunggah file Keybox XML/ZIP terbaru ke server. Langsung sedot mans!"},
                 "url": "https://siroevery.vercel.app/"
               }'
               
