name: Clone and Push to EXPERIMENTAL

on:
  workflow_dispatch:

jobs:
  clone-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Source Repo
        run: |
          git clone https://github.com/rahmatsobrian/kernel_xiaomi_rolex_4.9.240.git kernel
          cd kernel
          git remote remove origin
          git remote add origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/rahmatsobrian/EXPERIMENTALkernel_xiaomi_rolex_4.9.240.git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git branch -M main
          git add -A
          git commit -m "upload source" || echo "Nothing to commit"
          git push -u origin main --force
